name: ${name}
main: ${main}
version: ${version}
author: ${author}
description: ${description}
api-version: ${apiversion}
website: ${website}
depend:
  - "kLoader"
commands:
  build:
    description: Toggle build mode for players
    usage: /build [<player>]
    aliases: [ buildmode, baumodus ]